apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
   app: helloworld
spec:
  containers:
    - name: helloworld
      image: jyotisma/repo1:+ ":$BUILD_NUMBER"
      ports:
      - containerPort: 3000  
  
