export DOCKER_REGISTRY_SERVER=https://index.docker.io/v1/
export DOCKER_USER=jyotisma
export DOCKER_EMAIL=vjsrsr@gmail.com
export DOCKER_PASSWORD=docker@123

kubectl create secret docker-registry myregistrykey \
  --docker-server=$DOCKER_REGISTRY_SERVER \
  --docker-username=$DOCKER_USER \
  --docker-password=$DOCKER_PASSWORD \
  --docker-email=$DOCKER_EMAIL

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  containers:
    - name: whatever
      image: index.docker.io/jyotisma/repo1:51
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
  imagePullSecrets:
    - name: myregistrykey
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: docker.io/jyotisma/repo1:51
          ports:
            - containerPort: 8080
              protocol: TCP
