export DOCKER_REGISTRY_SERVER=https://index.docker.io/v1/
export DOCKER_USER=jyotisma
export DOCKER_EMAIL=vjsrsr@gmail.com
export DOCKER_PASSWORD=docker@123

kubectl create secret docker-registry myregistrykey \
  --docker-server=$DOCKER_REGISTRY_SERVER \
  --docker-username=$DOCKER_USER \
  --docker-password=$DOCKER_PASSWORD \
  --docker-email=$DOCKER_EMAIL

apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: helloworld
      image: index.docker.io/jyotisma/repo1:51
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
  imagePullSecrets:
    - name: myregistrykey
